# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps: 
- task: CmdLine@2
  inputs:
    script: 'pwd&&ls'
- task: DockerCompose@0
  displayName: "Compose build"
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'gunnarregistry.azurecr.io'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
- task: DockerCompose@0
  displayName: "Compose Push"
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'gunnarregistry.azurecr.io'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'
