version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          context: Azure
          name: "What the value of TEST_VARIABLE?"
          command: |
            echo ${TEST_VARIABLE}
            echo git-commit-tag:${CIRCLE_SHA1:0:7}
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      - run: 
          name: Build image
          context: Azure
          command: |
            env
            PATH=/tmp/docker/:$PATH
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t "${CONTAINER_REGISTRY}/circleci-storseilweb":$TAG .
      - run:
          name: "Publish image"
          context: Azure
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            COMMIT_TAG=${CIRCLE_SHA1:0:7}
            docker login -u "$CONTAINER_REGISTRY_USER" -p "$CONTAINER_REGISTRY_PASSWORD" "$CONTAINER_REGISTRY"
            echo "docker push $CONTAINER_REGISTRY/circleci-storseilweb:$TAG"
            docker push $CONTAINER_REGISTRY/circleci-storseilweb:$TAG
            echo "tag $CONTAINER_REGISTRY/circleci-storseilweb:$TAG $CONTAINER_REGISTRY/circleci-storseilweb:git-commit-$COMMIT_TAG"
            docker tag $CONTAINER_REGISTRY/circleci-storseilweb:$TAG $CONTAINER_REGISTRY/circleci-storseilweb:git-commit-$COMMIT_TAG
            docker push $CONTAINER_REGISTRY/circleci-storseilweb:git-commit-$COMMIT_TAG
            
