version: 2.1
jobs:
  build:
    context: "Azure"
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      - run: 
          name: Build image
          context: "Azure"
          command: |
            PATH=/tmp/docker/:$PATH
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $CONTAINER_REGISTRY/CircleCI-StorseilWeb:$TAG .
#      - run:
#       name: "Publish image"
#       context: Azure
#       command: |
#         docker login -u "$CONTAINER_REGISTRY_USER" -p "$CONTAINER_REGISTRY_PASSWORD" "$CONTAINER_REGISTRY"
#         docker push $CONTAINER_REGISTRY/CircleCI-StorseilWeb:$TAG
